server:
  port: 9090
  servlet:
    context-path: /v1/api/

spring:
  application:
    name: Vehicle Maintenance App
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_maintenance
    username: lorenzomallardo
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    
jwt:
  app:
    jwtCookieName: vehicle-maintenance
    jwtSecret: jwtsecret
    jwtExpirationMs: 86400000
    