server:
  port: 9090

spring:
  application:
    name: Vehicle Maintenance App
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_maintenance
    username: lorenzomallardo
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

    
security:
  secret: secretKey
  prefix: 'Bearer '
  param: Authorization
    
#logging:
#  level:
#    '[org.springframework]': trace